name: Bug report
description: (English)Submit a bug
labels: bug
title: '[Bug]: '
body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Check items
      description: Check out the inspection items
      options:
        - label: Using the latest IIE version
          required: true
        - label: >-
            Use the officially released version (not a third-party
            download/modified version)
          required: true
        - label: >-
            Have looked at the IIE official documentation and used all possible
            solutions
          required: true
        - label: >-
            Already re-entering in the editor interface/Already pressing the esc
            key to reset in the game interface
          required: true
        - label: Already tried restarting IIE
          required: true
        - label: Have browsed the Issues and found no duplicate Issues
          required: true
  - type: textarea
    id: '2'
    attributes:
      label: Symptoms of the bug
      description: Briefly describe the symptoms of the bug
    validations:
      required: true
  - type: textarea
    id: '3'
    attributes:
      label: Reproduction steps
      description: Briefly describe the steps you took to cause the bug
      value: |-
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: '4'
    attributes:
      label: Logs and screenshots
      description: >-
        Provide logs/screenshots/screen recordings, etc. to facilitate our
        troubleshooting
      placeholder: First click on this text box, then drag the file to upload it
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
